import Head from 'next/head';
import { Inter } from 'next/font/google';
import Hero from '@/sections/Hero';
import Price from '@/sections/Price';
import Features from '@/sections/Features';
import Steps from '@/sections/Steps';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Optochka.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="facebook-domain-verification" content="pvosf5ju9a4af54f7dkly8h8o81j2m" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div id="features">
          <Features />
          <Steps />
        </div>
        <div id="pricing">
          <Price />
        </div>
      </main>
    </>
  );
}
